### ISSUE TITLE
Cannot resolve DNS from inside vk

### ISSUE THREAD

**Issue by sdebruyn** [virtual-kubelet/azure-aci#549] opened 2023-05-26 10:16 UTC
**Describe the Issue**
When deploying a virtual kubelet, the kubelets cannot resolve any cluster DNS. It seems they have no route to the `kube-dns` service.

When resolving anything with `nslookup`, it always uses the second DNS server from /etc/resolv.conf: 168.63.129.16 since it seems unable to reach 10.0.0.10

DNS on the regular node works without issues.

**Steps To Reproduce**

- vnet address range: 10.48.0.0/19
- aks subnet: 10.48.0.0/21
- vk aci subnet: 10.48.8.0/21
- aks k8s version: 1.26
- aks service cidr: 10.0.0.0/16 (default)
- aks dns service ip: 10.0.0.10 (default)
- the vk addon profile identity has network contributor role on the vk aci subnet
- everything is in the west-europe region
- there are no NSGs linked to any subnet

aci subnet has service delegation (terraform):
```hcl
    service_delegation {
      name    = "Microsoft.ContainerInstance/containerGroups"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
```

aks cluster config (terraform):
```hcl
resource "azurerm_kubernetes_cluster" "main" {
  name                = "aks-redacted"
  location            = var.location
  resource_group_name = var.resource_group_name

  kubernetes_version  = var.kubernetes_version
  node_resource_group = "rg-redacted"

  dns_prefix                        = "aksredacted"
  azure_policy_enabled              = true
  http_application_routing_enabled  = false
  role_based_access_control_enabled = true
  oidc_issuer_enabled               = true
  local_account_disabled            = true

  azure_active_directory_role_based_access_control {
    managed                = true
    azure_rbac_enabled     = true
    admin_group_object_ids = ["redacted", "redacted"]
  }

  default_node_pool {
    name                 = "agentpool"
    node_count           = var.min_node_count
    vm_size              = var.vm_size
    vnet_subnet_id       = azurerm_subnet.worker_aks_subnet.id
    enable_auto_scaling  = true
    min_count            = var.min_node_count
    max_count            = var.max_node_count
    orchestrator_version = var.kubernetes_version
    max_pods             = var.max_pods_per_node_pool
    type                 = "VirtualMachineScaleSets"
    node_labels = {
      "role" = "master"
    }
  }

  # Enable virtual node (ACI connector) for Linux
  aci_connector_linux {
    subnet_name = azurerm_subnet.aci_virtualnode_subnet.name
  }

  network_profile {
    network_plugin = "azure"
    network_policy = "azure"
  }

  auto_scaler_profile {
    skip_nodes_with_local_storage = false
  }

  oms_agent {
    log_analytics_workspace_id = azurerm_log_analytics_workspace.main.id
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.main.id]
  }

  kubelet_identity {
    client_id                 = azurerm_user_assigned_identity.main.client_id
    object_id                 = azurerm_user_assigned_identity.main.principal_id
    user_assigned_identity_id = azurerm_user_assigned_identity.main.id
  }

  lifecycle {
    ignore_changes = [
      default_node_pool[0].node_count
    ]
  }

  ingress_application_gateway {
    gateway_id = azurerm_application_gateway.network.id
  }

  storage_profile {
    # Needed to mount Azure Blob Storage as a volume
    blob_driver_enabled = true
  }

  timeouts {
    create = "30m"
    delete = "90m"
  }
```

**Expected behavior**
DNS lookup to services in the "regular" node pool works

**Virtual-kubelet version**
Tried both latest add-on version as well as helm chart 1.5.1

**Kubernetes version**
1.26.3

It looks a lot like https://github.com/virtual-kubelet/virtual-kubelet/issues/456 but that seems to be fixed?

**Comment by sdebruyn** [comment] 2023-05-26 10:29
It looks a lot like #456 but that is an issue from years ago which should be fixed already

**Comment by sdebruyn** [comment] 2023-05-26 12:33
We also tried with `network_policy` set to none (recreated the cluster), but that did not resolve the issue.

**Comment by Fei-Guo** [comment] 2023-06-13 03:49
Did you enable authorized ip range in apiserver?

**Comment by jmarien** [comment] 2023-06-13 06:53
No, this was not enabled.

**Comment by Fei-Guo** [comment] 2023-06-13 16:44
A few things to try:
1) 10.0.0.10 is a cluster ip.  You can find the coredns pod ip and change the dns ip to real pod ip in etc/resolve.conf of the ACI instance (by `kubectl exec` into the pod). If this works, it means the kubeproxy running inside the ACI instance stops working for some reason. Otherwise, you have a networking connectivity issue. Also, ping apiserver's FQDN to see if it works.

2) If you upgrade your K8s cluster while the ACI instance was running. There is a chance that kubeproxy running inside VK fails to reconnect to the apiserver (can be due to the version mismatch between kubeproxy and apiserver). You can recreate a new ACI instance and see if the coredns works.

3) Check your container's base image. We found that for some old version of alpine image, there is a problem for dns resolution when two dns servers are listed in resolve.conf. You can change your container base image to a new version and see if the problem is resolved.

**Comment by jmarien** [comment] 2023-06-14 11:43
Thanks for the pointers @Fei-Guo - we will get back to you on these!

**Comment by helayoty** [comment] 2023-06-30 01:28
@jmarien can we close the issue?

**Closed** 2023-08-29 16:48 UTC
