### ISSUE TITLE
After scaling-down the containers, it happens sometimes that containers are left running in the ACI

### ISSUE THREAD

**Issue by eugen-nw** [virtual-kubelet/azure-aci#32] opened 2020-01-05 19:00 UTC
I've experienced this several times in the past, but unfortunately I have never noticed a pattern on how to repro the behavior.  'kubectl get pods' reports the same number of containers as the 'kubectl describe hpa' command (which is good), yet there are more of them running when I check the Container Instances service in the Azure Portal.

This is a fairly bad bug because people will end up paying for more container usage than what they actually need.  It'd be nice to document the behavior until a fix is in place.

**Comment by eugen-nw** [comment] 2020-01-05 20:03
Another interesting scenario that may be related.  'kubectl get pods' shows the output below, while all those STATUS = NotFound containers are up and running in ACI.  'kubectl describe hpa' says that 4 containers are running, which matches the STATUS = Running.

![image](https://user-images.githubusercontent.com/15199814/71785313-e1f78280-2fb2-11ea-85bb-7fd9a6a6a386.png)

**Comment by macolso** [comment] 2020-01-06 18:00
Thanks for bringing this to our attention! I know you haven't been able to get a repo, but it sounds like you've only noticed this pattern after scaling down your VN pods? 

@ibabou

**Comment by ibabou** [comment] 2020-01-06 18:10
@eugen-nw this was a bug that got fixed in the last release about a month ago. It was caused when VK attempts to delete the CG fails, and so it gives up leaving it running. the failures to delete were mostly happening because of throttling issues when talking to RP, which got handled better. Although, I see in the screenshot that you're using a windows connector. since this doesn't get deployed and updated automatically as an add-on like Linux one -- it is in-preview functionality, you'll need to re-install the latest version manually after removing the existing one (either through remove connector cli wrapper or directly through helm). Here is a command to install the latest version (please make sure to pass nodeName same to what you have currently on the cluster):
`helm install https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-aci-for-aks.tgz --generate-name --set nodeOsType=Windows --set nodeName=<the_name_of_node_they_are_currently_using> --set providers.azure.aciRegion=eastus --set image.name=virtual-kubelet --set image.tag=1.1.0.1 --set providers.azure.vnet.enabled=false --set providers.azure.vnet.subnetName=`

**Comment by scabana** [comment] 2020-01-06 18:46
Hello @ibabou , 

We have similar issues. 

I tried getting 1.1.0.1, but docker tells me it doesn't exist. Seems like last version is 0.9.1? (Error response from daemon: manifest for microsoft/virtual-kubelet:1.1.0.1 not found: manifest unknown: manifest unknown.). Am I looking in the right place? (https://hub.docker.com/r/microsoft/virtual-kubelet/tags)

Thanks!

**Comment by eugen-nw** [comment] 2020-01-06 19:11
Thanks very much @ibabou!  I'm REALLY glad that the issue is fixed now!  Although @scabana could not find it yet :-(

How can I tell please what version of the ACI connector I'm using?  The `kubectl describe deployment aci-connector-windows-eastus-virtual-kubelet-for-aks` command tells me:

![image](https://user-images.githubusercontent.com/15199814/71841864-36fbcd00-3075-11ea-8891-9015086e2253.png)

**Comment by eugen-nw** [comment] 2020-01-07 00:28
@scabana any luck with upgrading your VK please?

**Comment by ibabou** [comment] 2020-01-07 00:37
@scabana the VK connector for ACI is not pushed to the docker hub repo anymore. please use the helm chart I shared to install it (it has the new ACR repo information, as well as a read-only creds to it).

**Comment by eugen-nw** [comment] 2020-01-07 17:34
Is there a release notes document anywhere that we can consult to see what fixes & features are in each new version?

**Comment by macolso** [comment] 2020-01-07 18:53
https://github.com/virtual-kubelet/azure-aci/releases

**Comment by eugen-nw** [comment] 2020-01-07 19:12
Thanks very much!

I have a question on the "helm install..." command @ibabou provided please: I'd guess that providers.azure.aciRegion would be the region in which the ACI is, right?  However, Azure portal provides only one ACI instance and that has no region information attached.  I'm kind of uneasy with the 'eastus' value provided as my AKS instance is in 'westus'.  I took a peek into the azure-aci/helm/templates/deployment.yaml file, but does not offer enlightenment on the value.

**Comment by eugen-nw** [comment] 2020-01-07 20:55
The command line below created the new Deployment, a running Container that keeps failing and recreating itself (leaving the Failed ones) behind and no new virtual Node.  What is missing please?  

helm install https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-aci-for-aks.tgz --generate-name --set nodeOsType=Windows --set nodeName=aks-agentpool-42482945-0  --set providers.azure.aciRegion=westus --set image.name=virtual-kubelet --set image.tag=1.1.0.1 --set providers.azure.vnet.enabled=false --set providers.azure.vnet.subnetName=

Also, how do I remove this thing now?  Neither of the commands below work, both return 'Release name is invalid':

helm uninstall https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-aci-for-aks.tgz

helm uninstall virtual-kubelet-aci-for-aks-1578425326-virtual-kubelet-aci-for

**Comment by ibabou** [comment] 2020-01-07 20:59
@eugen-nw the aciRegion is optional, if not passed the region of AKS cluster will be used. Regarding the helm chart, nodeName is the name of virtual node (you can't use one of existing nodes like aks-agentpool-42482945-0). In the case above for example, it'll be virtual-kubelet-aci-connector-eastus. 
To delete from helm, use "helm list" and then copy the release name from there, and finally do a "helm uninstall <release name>".

**Comment by eugen-nw** [comment] 2020-01-07 21:16
Thanks very much!  The uninstall overdid things, it removed the virtual-node-aci-linux Node as well.

The command line below did not create a new Node either :-(  The Pod restarted already 3 times.

`helm install https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-aci-for-aks.tgz --generate-name --set nodeOsType=Windows --set nodeName=virtual-kubelet-aci-connector-for-windows  --set image.name=virtual-kubelet --set image.tag=1.1.0.1 --set providers.azure.vnet.enabled=false --set providers.azure.vnet.subnetName=`

**Comment by ibabou** [comment] 2020-01-07 21:29
Sure, no problem.

No the helm uninstall won't remove the old node. except if you did uninstall its release as well. @eugen-nw can you share the error, the logs from the failing pod ? I just tried now adding a node using the exact command to one of clusters using helm 3 and it worked fine.

Here is the trial:
ibabou@ibabou-ws-ubuntu:~/development/random$ helm install https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-aci-for-aks.tgz --generate-name --set nodeOsType=Windows --set nodeName=virtual-kubelet-aci-connector-for-windows --set image.name=virtual-kubelet --set image.tag=1.1.0.1 --set providers.azure.vnet.enabled=false --set providers.azure.vnet.subnetName=
NAME: virtual-kubelet-aci-for-aks-1578432175
LAST DEPLOYED: Tue Jan  7 13:22:56 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The virtual kubelet with Azure provider is getting deployed on your cluster.
To verify that virtual kubelet has started, run:
  kubectl --namespace=default describe deployment "virtual-kubelet-aci-for-aks"

ibabou@ibabou-ws-ubuntu:~/development/random$ kubectl get pods
NAME                                                              READY   STATUS    RESTARTS   AGE
virtual-kubelet-aci-for-aks-1578432175-virtual-kubelet-acilkrsg   1/1     Running   0          6s

ibabou@ibabou-ws-ubuntu:~/development/random$ kubectl get nodes
NAME                                        STATUS                     ROLES   AGE     VERSION
aks-agentpool-21844853-vmss000000           Ready                      agent   33d     v1.15.5
aks-agentpool-21844853-vmss000001           Ready,SchedulingDisabled   agent   33d     v1.15.5
virtual-kubelet-aci-connector-for-windows   Ready                      agent   2m32s   v1.14.3-vk-azure-aci-v1.1.0.1

ibabou@ibabou-ws-ubuntu:~/development/random$ kubectl get pods -o wide
NAME                                                              READY   STATUS    RESTARTS   AGE     IP            NODE                                NOMINATED NODE   READINESS GATES
virtual-kubelet-aci-for-aks-1578432175-virtual-kubelet-acilkrsg   1/1     Running   0          4m45s   10.240.0.34   aks-agentpool-21844853-vmss000000   <none>           <none>

0 restarts so far.

**Comment by eugen-nw** [comment] 2020-01-07 21:46
Thanks very much again!  I did one more experiment, it still does not work.  I upgraded Helm today to 3.0.2  Please find attached the log file.  It has this piece of information about the deleted node: "Deleting node virtual-node-aci-linux because it does not exist in the cloud provider"  That came with AKS, I'm fairly certain that I did not delete it; I'll check the history of past commands.

[logs.txt](https://github.com/virtual-kubelet/azure-aci/files/4032603/logs.txt)

**Comment by eugen-nw** [comment] 2020-01-07 21:58
Your command line is quite different from the one documented here: https://github.com/virtual-kubelet/azure-aci#manual-set-up  I'll try, maybe that sequence works.

**Comment by eugen-nw** [comment] 2020-01-07 22:41
I tried installing using the "combined" command line below.  The container still keeps restarting.  I stop spending time on this as there isn't anything more that I can do with my level of knowledge.  I'll let it produce logs for an hour and then attach the file.

$env:RELEASE_NAME="virtual-kubelet"
$env:VK_RELEASE="virtual-kubelet-aci-for-aks"
$env:MASTER_URI="https://eugen-aks-external-solver-ver2-e90bcafa.hcp.westus.azmk8s.io:44"
$env:NODE_NAME="virtual-kubelet-aci-connector-for-windows"
$env:CHART_URL="https://github.com/virtual-kubelet/azure-aci/raw/master/charts/"+$env:VK_RELEASE+".tgz"
helm install $env:CHART_URL --generate-name  --set nodeOsType=Windows --set provider=azure --set providers.azure.targetAKS=true --set providers.azure.masterUri=$env:MASTER_URI  --set image.name=virtual-kubelet  --set image.tag=1.1.0.1 --set providers.azure.vnet.enabled=false --set providers.azure.vnet.subnetName=

**Comment by ibabou** [comment] 2020-01-07 22:44
@eugen-nw Can you please try the command I pasted above as it is, without passing targetAKS or masterURI:
Here it is again:
'helm install https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-aci-for-aks.tgz --generate-name --set nodeOsType=Windows --set nodeName=virtual-kubelet-aci-connector-for-windows --set image.name=virtual-kubelet --set image.tag=1.1.0.1 --set providers.azure.vnet.enabled=false --set providers.azure.vnet.subnetName='

**Comment by eugen-nw** [comment] 2020-01-07 22:55
Certainly.  There's no improvement, please see the image below.  Now I see 2 containers instead of one, in spite of the fact that I started with none.  @scabana would you be interested in giving this installation a try?

![image](https://user-images.githubusercontent.com/15199814/71936249-bd8bd980-315d-11ea-8fd7-dfa8a3669a38.png)

**Comment by ibabou** [comment] 2020-01-07 23:08
I see. So can you please share why the pods are failing, what is the error, do you see logs ?

**Comment by eugen-nw** [comment] 2020-01-07 23:12
I'll let the pod/virtual-kubelet-aci-for-aks-1578437981-virtual-kubelet-* pods to fail for an hour and attach the log then.  Maybe we'll find some useful information in the very condensed K8S logs.

**Comment by eugen-nw** [comment] 2020-01-07 23:24
Could this have anything to do with the K8S version?  Or with the fact that I upgraded today only Helm and not Tiller?

**Comment by ibabou** [comment] 2020-01-07 23:27
Helm 3 doesn't require tiller as far as I know. Regarding logs, I think you don't need to wait to get the actual logs of these failing pods or the errors/cause of failure while starting up the connector container, I wasn't mentioning about other k8s logs anyway.

**Comment by eugen-nw** [comment] 2020-01-07 23:32
The earlier log I generated using: kubectl get events --sort-by='{.lastTimestamp}'

To my knowledge that grabs the K8S logs, but I may be wrong.  I'm very new at this, K8S is very big and I use only a fraction of it.

**Comment by ibabou** [comment] 2020-01-08 00:07
can you try "kubectl logs name_of_pod" to capture the recent logs from that failing pod.

**Comment by eugen-nw** [comment] 2020-01-08 16:56
Thanks again very much, I did not know of that command!

I left yesterday for home and the ACI connector works now.  That's the good news.  What I do not like about it is that it restarted 15 times.  Its age is 17h, the virtual-kubelete-aci... is 16h old, so in the first hour it was doing nothing else than restarting and for some unknown reason it started working.

Since I have the repro that you guys do not have, I am perfectly OK uninstalling the ACI connector, installing it again and get for you the logs that get generated during that stormy startup.  Please let me know.

![image](https://user-images.githubusercontent.com/15199814/71998467-8e747700-31f4-11ea-882d-3fe514310190.png)

**Comment by eugen-nw** [comment] 2020-01-08 17:05
I would not worry about this error because I did not install yet any container to run on top of the ACI connector.

`level=error msg="failed to fetch the list of pods from the provider: Sending get container group list request failed: Get https://management.azure.com/subscriptions/d1151462-af84-4066-8ebc-62a4191a356e/resourceGroups/MC_eugen-prototypes-west-us_eugen-aks-external-solver-ver2_westus/providers/Microsoft.ContainerInstance/containerGroups?api-version=2018-10-01: dial tcp: lookup management.azure.com on 10.0.0.10:53: no such host" method=deleteDanglingPods node=virtual-kubelet-aci-connector-for-windows operatingSystem=Windows provider=azure watchedNamespace=`

**Comment by ibabou** [comment] 2020-01-08 18:32
@eugen-nw 
Thanks for sharing the logs!

The URL it tries to use to retrieve all CGs related to this VN seems correct to me, this cleanup operation in a on-time execution that happens at the beginning and it should succeed normally. the ACI resources needs to be under a ResourceGroup. If you browse in the portal to "/resource/subscriptions/d1151462-af84-4066-8ebc-62a4191a356e/resourceGroups/MC_eugen-prototypes-west-us_eugen-aks-external-solver-ver2_westus/overview", you should be able to see all non-managed resources of your AKS cluster in addition to any ACI CGs that got created.

Now looks like there is a connectivity issue to ARM (management.azure.com), the endpoint that receives all Azure RPs related requests (including all CRUD ops for ACI). and I think that's why it failed in the initialization sometimes, faileled later after startup sometimes, and later again being fine as you mentioned. if the issue is a misconfiguration or bad handling, it'll be a consistent failure. 

This error is very weird, it should be able to resolve ARM endpoint:
dial tcp: lookup management.azure.com on 10.0.0.10:53: no such host

Can you please try to repro, I just want to make sure that this wasn't because of a connectivity issue. Also, can you try to repro the crash on the startup ? and share the logs for this ? As errors doesn't mean the connector will fail, in many cases the operations is just retried.

**Comment by eugen-nw** [comment] 2020-01-08 19:15
I see how it works, thanks very much for the clarification!  I walked through what you wrote and have noticed that the ACI connector labels the containers it creates with NodeName, which I suspect is the attribute you use to filter the dangling containers.  You wrote that 

> this cleanup operation in a on-time execution that happens at the beginning

In order to fix the issue at hand, that cleanup needs to execute as well on a schedule, right?  No customer wants to pay for dangling containers left over running in ACI.

No problem at all to repro for you!  I Helm-uninstalled & installed again using yesterday's most recent command: `helm install https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-aci-for-aks.tgz --generate-name --set nodeOsType=Windows --set nodeName=virtual-kubelet-aci-connector-for-windows --set image.name=virtual-kubelet --set image.tag=1.1.0.1 --set providers.azure.vnet.enabled=false --set providers.azure.vnet.subnetName=`

I ran into an issue, the problem no longer repro-es: the pod runs flawlessly and the virtual node was created.  How I hate it whenever that happens AND I do not have logs of the bad behavior!  You guys may want to add a new option to the ACI connector to take an App Insights Instrumentation Key (GUID) and if that GUID is present, then log there.  If we'd had that in place yesterday, we'd have the logs now.

Oh well, onto a brilliant new day!  Thanks very much for all your help Ibrahim!

**Comment by ibabou** [comment] 2020-01-08 19:25
@eugen-nw that's great to hear :). glad to help!

You are right to some extend, however the purpose of having it on startup only was to handle the cases when the connector crashes or when being replaced -- in this case we might know what was the last incomplete operations that happened on CGs. But actually in v1.2 (upcoming release), I'll keep a cleanup job in the background to periodically do so, just to handle any other cases we're not counting for.

Regarding app insights, this is already available to some extend, so if your AKS cluster already setup for LA. you can collect the logs of VK connector and push it there like any other workload running in your cluster. It's even more, the logs containers running on ACI side (on the virtual node) will be forwarded to same LA workspace as well.

**Closed** 2020-01-08 19:27 UTC

**Comment by eugen-nw** [comment] 2020-01-08 19:35
> But actually in v1.2 (upcoming release), I'll keep a cleanup job in the background to periodically do so, just to handle any other cases we're not counting for.

If that's the current behavior, then the problem I raised when I opened this issue is not fixed yet :-(  
The ongoing cleanup of dangling containers is important so customers do not pay for unused containers left over in ACI.  When is 1.2 going to be released please?

**Comment by ibabou** [comment] 2020-01-08 20:06
No, but the dangling happened in your case because you were running v0.9 where we had a bug preventing us from handling the deletion correctly. With v1.1, this got fixed. But what I mentioned is an additional guard to make us safe in future if any similar issues happened.

**Comment by eugen-nw** [comment] 2020-01-08 20:29
Thank you.  Let me test it for a day or two.

Do you happen to have a ballpark estimate for the 1.2 release date?

**Comment by eugen-nw** [comment] 2020-01-08 20:37
I noticed in the AKS instance -> Logs -> ContainerInstances -> ContainerLog table.  Would you like me to export yesterday's content to you?

**Comment by macolso** [comment] 2020-01-09 17:29
We're hoping to get 1.2 out this week! I'll let @ibabou get back to you about the logs

**Comment by ibabou** [comment] 2020-01-13 20:05
@eugen-nw 1.2.1 is [released](https://github.com/virtual-kubelet/azure-aci/releases/tag/v1.2.1) now, you can try installing it through same helm chart (tag=1.2.1).

**Comment by eugen-nw** [comment] 2020-01-14 03:35
Thanks very much guys!  I've installed it with this command line (I updated the --set image.tag to the current version:
`helm install https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-aci-for-aks.tgz --generate-name --set nodeOsType=Windows --set nodeName=virtual-kubelet-aci-connector-for-windows --set image.name=virtual-kubelet --set image.tag=1.2.1 --set providers.azure.vnet.enabled=false --set providers.azure.vnet.subnetName=`

The previous version did an amazing job in deleting dangling ACI instances!  None left over in ACI during a 48 hours test where I created a scale-out event every 30 minutes.  I'm about to start testing the 1.2.1 version, thanks again!

**Comment by eugen-nw** [comment] 2020-01-15 16:39
@ibabou I'm very sorry to inform, but 1.2.1 generates in ACI one more container than what's in K8S :-(  I manually scaled the deployment that runs on the Virtual Kubelet to 3 instances and ACI shows four containers instead of 3.

This is the situation in K8S:
![image](https://user-images.githubusercontent.com/15199814/72452324-37315200-3772-11ea-9793-7137b87fae6c.png)

And this is what ACI shows:
![image](https://user-images.githubusercontent.com/15199814/72452411-5c25c500-3772-11ea-987f-ca35cece26db.png)

**Comment by eugen-nw** [comment] 2020-01-15 16:42
Scaling up to 6 resulted in 7 containers in ACI and scaling down to 1 => 2 containers in ACI.  So the behavior is consistent.
